
import javax.swing.JOptionPane;

public class MainScreen extends javax.swing.JFrame {

  /**
   * Creates new form MainScreen
   */
  public MainScreen() {
    initComponents();
    try {
      DbConnect dbObj = new DbConnect("tblNetworkDevices.accdb");
      txtTableDisplay.setText(dbObj.displayAll());
    } catch (ClassNotFoundException e) {
      JOptionPane.showMessageDialog(null, "Error creating dbConnect class");
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Main = new javax.swing.JPanel();
    TopBar = new javax.swing.JPanel();
    lblLocateRecord = new javax.swing.JLabel();
    lblOrderBy = new javax.swing.JLabel();
    txtSearchBar = new javax.swing.JTextField();
    jSpinner1 = new javax.swing.JSpinner();
    btnSearch = new javax.swing.JButton();
    btnSort = new javax.swing.JButton();
    BottomBar = new javax.swing.JPanel();
    txtTableDisplay = new javax.swing.JTextPane();
    jPanel2 = new javax.swing.JPanel();
    btnUpdate = new javax.swing.JButton();
    btnAdd = new javax.swing.JButton();
    btnSumPrice = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(750, 425));

    lblLocateRecord.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblLocateRecord.setText("Locate Record: ");

    lblOrderBy.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblOrderBy.setText("Order by:  ");

    txtSearchBar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    txtSearchBar.setText("Enter Device Name");

    jSpinner1.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"Device", "Price", "NumberOfPorts", "Protocol", "SignalBoosting"}));

    btnSearch.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    btnSearch.setText("Search");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });

    btnSort.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    btnSort.setText("Sort");
    btnSort.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSortActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
    TopBar.setLayout(TopBarLayout);
    TopBarLayout.setHorizontalGroup(
      TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TopBarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblLocateRecord)
          .addComponent(lblOrderBy))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
          .addComponent(jSpinner1))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSort, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );
    TopBarLayout.setVerticalGroup(
      TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TopBarLayout.createSequentialGroup()
        .addGap(17, 17, 17)
        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblLocateRecord)
          .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSearch))
        .addGap(18, 18, 18)
        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblOrderBy)
          .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnSort))
        .addContainerGap(41, Short.MAX_VALUE))
    );

    txtTableDisplay.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
    txtTableDisplay.setAutoscrolls(false);

    btnUpdate.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    btnUpdate.setText("Update");
    btnUpdate.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnUpdateActionPerformed(evt);
      }
    });

    btnAdd.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    btnAdd.setText("Add");
    btnAdd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAddActionPerformed(evt);
      }
    });

    btnSumPrice.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    btnSumPrice.setText("Sum");
    btnSumPrice.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSumPriceActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
      .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(btnSumPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(btnAdd)
        .addGap(18, 18, 18)
        .addComponent(btnUpdate)
        .addGap(18, 18, 18)
        .addComponent(btnSumPrice)
        .addContainerGap(52, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout BottomBarLayout = new javax.swing.GroupLayout(BottomBar);
    BottomBar.setLayout(BottomBarLayout);
    BottomBarLayout.setHorizontalGroup(
      BottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(BottomBarLayout.createSequentialGroup()
        .addContainerGap(18, Short.MAX_VALUE)
        .addComponent(txtTableDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    BottomBarLayout.setVerticalGroup(
      BottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(BottomBarLayout.createSequentialGroup()
        .addGap(9, 9, 9)
        .addGroup(BottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(txtTableDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(50, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
    Main.setLayout(MainLayout);
    MainLayout.setHorizontalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
      .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(BottomBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    MainLayout.setVerticalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(286, Short.MAX_VALUE))
      .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
          .addGap(0, 142, Short.MAX_VALUE)
          .addComponent(BottomBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 756, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 448, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(Main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    try {
      DbConnect dbObj = new DbConnect("tblNetworkDevices.accdb");
      txtTableDisplay.setText(dbObj.displaySingle(txtSearchBar.getText()));
    } catch (ClassNotFoundException e) {
      JOptionPane.showMessageDialog(null, "Error locating record");
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
    try {
      DbConnect dbObj = new DbConnect("tblNetworkDevices.accdb");
      txtTableDisplay.setText(dbObj.sortTable(jSpinner1.getValue().toString()));
    } catch (ClassNotFoundException e) {
      JOptionPane.showMessageDialog(null, "Error sorting table");
    }
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    this.setVisible(false);
    new AddScreen().setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

  private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    this.setVisible(false);
    new UpdateScreen().setVisible(true);
  }//GEN-LAST:event_btnUpdateActionPerformed

  private void btnSumPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumPriceActionPerformed
    try {
      DbConnect dbObj = new DbConnect("tblNetworkDevices.accdb");
      txtTableDisplay.setText(dbObj.getSum());
    } catch (ClassNotFoundException e) {
      JOptionPane.showMessageDialog(null, "Error sorting table");
    }
  }//GEN-LAST:event_btnSumPriceActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainScreen().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel BottomBar;
  private javax.swing.JPanel Main;
  private javax.swing.JPanel TopBar;
  private javax.swing.JButton btnAdd;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton btnSort;
  private javax.swing.JButton btnSumPrice;
  private javax.swing.JButton btnUpdate;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JSpinner jSpinner1;
  private javax.swing.JLabel lblLocateRecord;
  private javax.swing.JLabel lblOrderBy;
  private javax.swing.JTextField txtSearchBar;
  private javax.swing.JTextPane txtTableDisplay;
  // End of variables declaration//GEN-END:variables
}
