
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nngob
 */
public class UpdateScreen extends javax.swing.JFrame {

  /**
   * Creates new form UpdateScreen
   */
  public UpdateScreen() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    Main = new javax.swing.JPanel();
    TopBar = new javax.swing.JPanel();
    lblLocateRecord = new javax.swing.JLabel();
    txtSearchBar = new javax.swing.JTextField();
    btnSearch = new javax.swing.JButton();
    LeftLabels = new javax.swing.JPanel();
    lblDeviceName = new javax.swing.JLabel();
    lblPrice = new javax.swing.JLabel();
    lblDescription = new javax.swing.JLabel();
    lblNumOfPorts = new javax.swing.JLabel();
    lblProtocol = new javax.swing.JLabel();
    lblProtocol1 = new javax.swing.JLabel();
    RightInputs = new javax.swing.JPanel();
    txtDeviceName = new javax.swing.JTextField();
    txtDevicePrice = new javax.swing.JTextField();
    txtDeviceNumOfPorts = new javax.swing.JTextField();
    txtDefinition = new javax.swing.JTextField();
    tglBtnSignalBoosting = new javax.swing.JRadioButton();
    txtProtocol = new javax.swing.JTextField();
    btnUpdateRecord = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    lblLocateRecord.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblLocateRecord.setText("Locate Record: ");

    txtSearchBar.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    txtSearchBar.setText("Enter Device Name");

    btnSearch.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    btnSearch.setText("Locate");
    btnSearch.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSearchActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
    TopBar.setLayout(TopBarLayout);
    TopBarLayout.setHorizontalGroup(
      TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TopBarLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblLocateRecord)
        .addGap(18, 18, 18)
        .addComponent(txtSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        .addGap(18, 18, 18)
        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    TopBarLayout.setVerticalGroup(
      TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(TopBarLayout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lblLocateRecord)
          .addComponent(btnSearch)
          .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(27, Short.MAX_VALUE))
    );

    lblDeviceName.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblDeviceName.setText("Device Name :");

    lblPrice.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblPrice.setText("Price :");

    lblDescription.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblDescription.setText("Description :");

    lblNumOfPorts.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblNumOfPorts.setText("Num. of Ports :");

    lblProtocol.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblProtocol.setText("Signal Boosting :");

    lblProtocol1.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    lblProtocol1.setText("Protocol :");

    javax.swing.GroupLayout LeftLabelsLayout = new javax.swing.GroupLayout(LeftLabels);
    LeftLabels.setLayout(LeftLabelsLayout);
    LeftLabelsLayout.setHorizontalGroup(
      LeftLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LeftLabelsLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(LeftLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lblDeviceName, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblDescription, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblProtocol1, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblPrice, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblNumOfPorts, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(lblProtocol, javax.swing.GroupLayout.Alignment.TRAILING))
        .addContainerGap())
    );
    LeftLabelsLayout.setVerticalGroup(
      LeftLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(LeftLabelsLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lblDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblNumOfPorts, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblProtocol1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(lblProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    txtDeviceName.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    txtDeviceName.setText("Enter Device Name");

    txtDevicePrice.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    txtDevicePrice.setText("Enter Device Price");

    txtDeviceNumOfPorts.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    txtDeviceNumOfPorts.setText("Enter Number of Ports");

    txtDefinition.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    txtDefinition.setText("Describe Device Functionality");

    tglBtnSignalBoosting.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    tglBtnSignalBoosting.setText("Signal Boosting");
    tglBtnSignalBoosting.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        tglBtnSignalBoostingActionPerformed(evt);
      }
    });

    txtProtocol.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    txtProtocol.setText("Describe Device Functionality");
    txtProtocol.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtProtocolActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout RightInputsLayout = new javax.swing.GroupLayout(RightInputs);
    RightInputs.setLayout(RightInputsLayout);
    RightInputsLayout.setHorizontalGroup(
      RightInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(RightInputsLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(RightInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtDevicePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
          .addComponent(txtDeviceName, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
          .addComponent(txtDeviceNumOfPorts, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
          .addComponent(txtDefinition, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
          .addGroup(RightInputsLayout.createSequentialGroup()
            .addComponent(tglBtnSignalBoosting)
            .addGap(0, 0, Short.MAX_VALUE))
          .addComponent(txtProtocol, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE))
        .addContainerGap())
    );
    RightInputsLayout.setVerticalGroup(
      RightInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(RightInputsLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(txtDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(txtDevicePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(txtDeviceNumOfPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(txtDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(20, 20, 20)
        .addComponent(txtProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(tglBtnSignalBoosting, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(19, Short.MAX_VALUE))
    );

    btnUpdateRecord.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
    btnUpdateRecord.setText("Update Record");
    btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnUpdateRecordActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
    Main.setLayout(MainLayout);
    MainLayout.setHorizontalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(MainLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btnUpdateRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(MainLayout.createSequentialGroup()
            .addComponent(LeftLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(RightInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(20, Short.MAX_VALUE))
      .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(MainLayout.createSequentialGroup()
          .addContainerGap()
          .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addContainerGap()))
    );
    MainLayout.setVerticalGroup(
      MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
        .addContainerGap(88, Short.MAX_VALUE)
        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(MainLayout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(RightInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
            .addComponent(LeftLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(14, 14, 14)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnUpdateRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(19, 19, 19))
      .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(MainLayout.createSequentialGroup()
          .addGap(16, 16, 16)
          .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(397, Short.MAX_VALUE)))
    );

    getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
    try {
      DbConnect dbObj = new DbConnect("tblNetworkDevices.accdb");
      String[] entry = dbObj.getSingleRecord(txtSearchBar.getText());

      // Sets values for fields
      txtSearchBar.setText(entry[0]);
      txtDeviceName.setText(entry[0]);
      txtDevicePrice.setText(entry[1]);
      txtDeviceNumOfPorts.setText(entry[2]);
      txtProtocol.setText(entry[3]);
      txtDefinition.setText(entry[4]);
      tglBtnSignalBoosting.setSelected(entry[5].equalsIgnoreCase("TRUE"));
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Error: " + e);
    }
  }//GEN-LAST:event_btnSearchActionPerformed

  private void txtProtocolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProtocolActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtProtocolActionPerformed

  private void tglBtnSignalBoostingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtnSignalBoostingActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tglBtnSignalBoostingActionPerformed

  private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
    try {
      // Gets Values for record
      String device = txtDeviceName.getText();
      Double price = Double.parseDouble(txtDevicePrice.getText());
      int numOfPorts = Integer.parseInt(txtDeviceNumOfPorts.getText());
      String description = txtDefinition.getText();
      boolean signalBoosting = tglBtnSignalBoosting.isSelected();
      String protocol = txtProtocol.getText();

      // Creates the record
      try {
        DbConnect dbObj = new DbConnect("tblNetworkDevices.accdb");
        dbObj.updateField(txtSearchBar.getText(), device, price, numOfPorts, protocol, description, signalBoosting ? "TRUE" : "FALSE");
      } catch (ClassNotFoundException e) {
        JOptionPane.showMessageDialog(null, "Error creating record");
      }

      // Goes back to main screen
      this.setVisible(false);
      new MainScreen().setVisible(true);
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Error in input validaion: " + e);
    }

  }//GEN-LAST:event_btnUpdateRecordActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(UpdateScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new UpdateScreen().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel LeftLabels;
  private javax.swing.JPanel Main;
  private javax.swing.JPanel RightInputs;
  private javax.swing.JPanel TopBar;
  private javax.swing.JButton btnSearch;
  private javax.swing.JButton btnUpdateRecord;
  private javax.swing.JLabel lblDescription;
  private javax.swing.JLabel lblDeviceName;
  private javax.swing.JLabel lblLocateRecord;
  private javax.swing.JLabel lblNumOfPorts;
  private javax.swing.JLabel lblPrice;
  private javax.swing.JLabel lblProtocol;
  private javax.swing.JLabel lblProtocol1;
  private javax.swing.JRadioButton tglBtnSignalBoosting;
  private javax.swing.JTextField txtDefinition;
  private javax.swing.JTextField txtDeviceName;
  private javax.swing.JTextField txtDeviceNumOfPorts;
  private javax.swing.JTextField txtDevicePrice;
  private javax.swing.JTextField txtProtocol;
  private javax.swing.JTextField txtSearchBar;
  // End of variables declaration//GEN-END:variables
}
